apiVersion: v1
kind: Namespace
metadata:
  name: sample
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helloworld
  namespace: sample
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  namespace: sample
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: helloworld-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/part-of: sample
    app.kubernetes.io/version: v1
  name: helloworld
  namespace: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-svc
      version: v1
  template:
    metadata:
      labels:
        app: helloworld-svc
        version: v1
    spec:
      containers:
      - image: tgrziminiar/go-hello:v.0.0.2
        name: helloworld-svc
        ports:
        - containerPort: 5000
          name: http
        resources:
          requests:
            cpu: 100m
      serviceAccountName: helloworld
